site_name: Fundamentos de Arquitetura de Computadores
repo_url: https://github.com/arthurrochamoreira/fac
repo_name: fac
extra_css:
  - css/custom-general.css
  - css/night-sky.css
  - css/shooting-stars.css
extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - js/interactive.js
  - js/shooting-stars.js
  - js/starfield.js
  - js/night-sky.js

plugins:
  - search
  - mermaid2

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.index
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - announce.dismiss

  language: pt-BR
  font:
    text: Roboto Mono
    code: Roboto Mono
    heading: Montserrat

  palette:
    - scheme: slate
      primary: deep purple
      accent: deep orange


nav:
  - Home: index.md
  # - MC/DC:
  #    - Modified Condition/Decision Coverage (MC/DC): aae3/mc_dc.md
  # - AAE:
  # - AAE3: aae3/aae3.md
  - Modulo 1: modulos/modulo 1/mod1.md
  - Modulo 2: modulos/modulo 2/mod2.md
  - Modulo 3: modulos/modulo 3/mod3.md
  - Modulo 4: 
    - Modulo 4.1: modulos/modulo 4/mod4.1_instrucoes_de_imediato.md
    - Modulo 4.2:  modulos/modulo 4/mod4.2_movimentacoes_de_dados.md
    - Modulo 4.3:  modulos/modulo 4/mod4.3_aritmetica_basica.md
    - Modulo 4.4:  modulos/modulo 4/mod4.4_comparacoes_e_desvios.md
    - Modulo 4.5:  modulos/modulo 4/mod4.5_saltos.md

  #    - Teste de Unidade: aae3/unit_test.md
  # - White-Box Testing:
  #    - Teste Caixa Branca: aae3/white_box_test.md
